name: MVP Requirements Check
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "research/**"

jobs:
  update:
    name: Update AutoML API
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.10
          cache: pip

      - name: Install requirements
        run: pip install -r mvp/requirements.txt

      # - name: Run tests
      #   run: python -B -m pytest